version: '3'
services:
  postgres:
    image: postgres:latest
    networks:
      - todo_network
    ports:
      - '5432:5432'
  mongo:
    image: mongo:latest
    networks:
      - todo_network
    ports:
      - '27017:27017'
  todoApp:
    networks:
      - todo_network
    ports:
      - '3769:9285'
    build:
      context: ./
      dockerfile: 'dockerfile'
      target: 'build'
    command: sh -c "npm run start:dev"
    restart: 'unless-stopped'
    env_file:
      - .env
    volumes:
      - .:/home/node
      - ./node_modules:/home/node
    depends_on:
      - postgres
      - mongo

networks:
  todo_network:
    driver: bridge
